{-# OPTIONS --experimental-lossy-unification #-}

---------------------------------------------------------
-- Free graded monad generated by algebraic operations --
---------------------------------------------------------

module Semantics.Model.Examples.TSets.Monad.Strength.Properties.Algebraicity where

open import Function

open import Data.Empty
open import Data.Product renaming (map to mapˣ)
open import Data.Unit hiding (_≤_)

open import Semantics.Model.Examples.TSets.TSets
open import Semantics.Model.Examples.TSets.Modality.Future
open import Semantics.Model.Examples.TSets.Modality.Past
open import Semantics.Model.Examples.TSets.Modality.Adjunction
open import Semantics.Model.Examples.TSets.Monad.Core
open import Semantics.Model.Examples.TSets.Monad.Strength
open import Semantics.Model.Examples.TSets.Monad.Effects

open import Semantics.Model.Category.Derived TSetCat
open import Semantics.Model.Modality.Adjunction.Derived TSetCat TSetFut TSetPas TSetAdj

open import Util.Equality
open import Util.Operations
open import Util.Time

-- Algebraicity of the delay operation wrt strength

strᵀ-delayᵀ-algebraicity : ∀ {A B τ τ'}
                         →     strᵀ {A} {B} {τ + τ'}
                            ∘ᵗ mapˣᵗ idᵗ (delayᵀ τ {τ'})
                         ≡ᵗ    delayᵀ τ
                            ∘ᵗ [ τ ]ᶠ (strᵀ {A} {B} {τ'})
                            ∘ᵗ []-monoidal {[ τ' ]ᵒ A} {Tᵒ B τ'}
                            ∘ᵗ mapˣᵗ (δ {A} {τ} {τ'}) idᵗ
strᵀ-delayᵀ-algebraicity {A} {B} {τ} {τ'} =
  eqᵗ (λ c →
    cong (delay-node τ)
      (sym
        (trans
          (cong₂ strˢ (monotone-trans A _ _ _) (Tˢ-≤t-trans _ _ _))
          (trans
            (cong₂ strˢ
              (monotone-trans A _ _ _)
              (trans (cong (λ p → Tˢ-≤t p (proj₂ c)) (≤-irrelevant _ _)) (Tˢ-≤t-refl _)))
            (cong (λ x → strˢ x (proj₂ c))
              (cong (λ p → monotone A p (proj₁ c)) (≤-irrelevant _ _)))))))

-- Algebraicity of algebraic operations wrt strength

-- TODO: One of the very slow proofs because unfolding of definition produces
--       humongous internal terms, complicating implicit argument resolution.

postulate
  strᵀ-opᵀ-algebraicity : ∀ {A B τ} → (op : Op)
                        →    strᵀ {A} {B}
                          ∘ᵗ mapˣᵗ
                               {[ op-time op + τ ]ᵒ A} {⟦ param op ⟧ᵍ ×ᵗ ([ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ))}
                               idᵗ (opᵀ op)
                       ≡ᵗ    opᵀ op
                          ∘ᵗ mapˣᵗ {⟦ param op ⟧ᵍ} {[ op-time op + τ ]ᵒ A ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                               idᵗ
                               (   [ op-time op ]ᶠ (   map⇒ᵐ {⟦ arity op ⟧ᵍ} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ} {Tᵒ (A ×ᵗ B) τ} idᵗ (strᵀ {A} {B} {τ})
                                                    ∘ᵗ curryᵗ
                                                         {[ τ ]ᵒ A ×ᵗ ((⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ))} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ}
                                                         ⟨    fstᵗ {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                                                           ∘ᵗ fstᵗ {_} {⟦ arity op ⟧ᵍ} ,
                                                           uncurryᵗ
                                                             {[ τ ]ᵒ A ×ᵗ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} {⟦ arity op ⟧ᵍ} {Tᵒ B τ}
                                                             (sndᵗ {[ τ ]ᵒ A}) ⟩ᵗ)
                                ∘ᵗ []-monoidal {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                                ∘ᵗ mapˣᵗ
                                     {[ op-time op + τ ]ᵒ A} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                                     {[ op-time op ]ᵒ ([ τ ]ᵒ A)} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                                     (δ {A} {op-time op} {τ}) idᵗ)
                          ∘ᵗ ⟨    fstᵗ {⟦ param op ⟧ᵍ} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                               ∘ᵗ sndᵗ {[ op-time op + τ ]ᵒ A} ,
                               ⟨ fstᵗ {[ op-time op + τ ]ᵒ A} {⟦ param op ⟧ᵍ ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} ,
                                    sndᵗ {⟦ param op ⟧ᵍ} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                                 ∘ᵗ sndᵗ {[ op-time op + τ ]ᵒ A} {⟦ param op ⟧ᵍ ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} ⟩ᵗ ⟩ᵗ
{-
strᵀ-opᵀ-algebraicity {A} {B} {τ} op =
  eqᵗ λ { {t} (v , w , k) →
    begin
      map-carrier
        (   strᵀ {A} {B}
         ∘ᵗ mapˣᵗ
              {[ op-time op + τ ]ᵒ A} {⟦ param op ⟧ᵍ ×ᵗ ([ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ))}
              idᵗ (opᵀ op))
        (v , w , k)
    ≡⟨⟩
      strˢ {A} {B} {_} {t}
        v
        (op-node {τ = τ}
          op
          w
          (λ p y → map-carrier k (p , y))
          λ p q y → map-nat k p (q , y))
    ≡⟨⟩
      op-node op w
        (λ p y →
           strˢ
           (monotone A
            (≤-trans (≤-reflexive (sym (+-assoc t (op-time op) τ)))
             (+-monoˡ-≤ τ p))
            v)
           (map-carrier k (p , y)))
        (λ p q y →
           trans
           (cong₂ strˢ
            (trans
             (cong (λ p₁ → monotone A p₁ v)
              (≤-irrelevant
               (≤-trans (≤-reflexive (sym (+-assoc t (op-time op) τ)))
                (+-monoˡ-≤ τ (≤-trans q p)))
               (≤-trans
                (≤-trans (≤-reflexive (sym (+-assoc t (op-time op) τ)))
                 (+-monoˡ-≤ τ q))
                (+-mono-≤ p ≤-refl))))
             (sym
              (monotone-trans A
               (≤-trans (≤-reflexive (sym (+-assoc t (op-time op) τ)))
                (+-monoˡ-≤ τ q))
               (+-mono-≤ p ≤-refl) v)))
            (map-nat k p (q , y)))
           (strˢ-≤t-nat p
            (monotone A
             (≤-trans (≤-reflexive (sym (+-assoc t (op-time op) τ)))
              (+-monoˡ-≤ τ q))
             v)
            (map-carrier k (q , y))))
    ≡⟨ {!!} ⟩
      map-carrier (opᵀ op)
        (w ,
         map-carrier
           (   [ op-time op ]ᶠ (   map⇒ᵐ {⟦ arity op ⟧ᵍ} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ} {Tᵒ (A ×ᵗ B) τ} idᵗ (strᵀ {A} {B} {τ})
                                ∘ᵗ curryᵗ
                                     {[ τ ]ᵒ A ×ᵗ ((⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ))} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ}
                                     ⟨    fstᵗ {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                                       ∘ᵗ fstᵗ {_} {⟦ arity op ⟧ᵍ} ,
                                       uncurryᵗ
                                         {[ τ ]ᵒ A ×ᵗ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} {⟦ arity op ⟧ᵍ} {Tᵒ B τ}
                                         (sndᵗ {[ τ ]ᵒ A}) ⟩ᵗ)
            ∘ᵗ [ op-time op ]ᶠ ⟨ ε⊣ ∘ᵗ ⟨ op-time op ⟩ᶠ fstᵗ , ε⊣ ∘ᵗ ⟨ op-time op ⟩ᶠ sndᵗ ⟩ᵗ
            ∘ᵗ η⊣ {τ = op-time op})
           (monotone A (≤-reflexive (sym (+-assoc t (op-time op) τ))) v , k))
    ≡⟨⟩
      map-carrier (opᵀ op)
        (w ,
         map-carrier
           (   [ op-time op ]ᶠ (   map⇒ᵐ {⟦ arity op ⟧ᵍ} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ} {Tᵒ (A ×ᵗ B) τ} idᵗ (strᵀ {A} {B} {τ})
                                ∘ᵗ curryᵗ
                                     {[ τ ]ᵒ A ×ᵗ ((⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ))} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ}
                                     ⟨    fstᵗ {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                                       ∘ᵗ fstᵗ {_} {⟦ arity op ⟧ᵍ} ,
                                       uncurryᵗ
                                         {[ τ ]ᵒ A ×ᵗ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} {⟦ arity op ⟧ᵍ} {Tᵒ B τ}
                                         (sndᵗ {[ τ ]ᵒ A}) ⟩ᵗ)
            ∘ᵗ []-monoidal {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ} {op-time op})
           (monotone A (≤-reflexive (sym (+-assoc t (op-time op) τ))) v , k))
    ≡⟨⟩
      map-carrier (opᵀ op)
        (w ,
         map-carrier
           (   [ op-time op ]ᶠ (   map⇒ᵐ {⟦ arity op ⟧ᵍ} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ} {Tᵒ (A ×ᵗ B) τ} idᵗ (strᵀ {A} {B} {τ})
                                ∘ᵗ curryᵗ
                                     {[ τ ]ᵒ A ×ᵗ ((⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ))} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ}
                                     ⟨    fstᵗ {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                                       ∘ᵗ fstᵗ {_} {⟦ arity op ⟧ᵍ} ,
                                       uncurryᵗ
                                         {[ τ ]ᵒ A ×ᵗ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} {⟦ arity op ⟧ᵍ} {Tᵒ B τ}
                                         (sndᵗ {[ τ ]ᵒ A}) ⟩ᵗ)
            ∘ᵗ []-monoidal {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
            ∘ᵗ mapˣᵗ
                 {[ op-time op + τ ]ᵒ A} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                 {[ op-time op ]ᵒ ([ τ ]ᵒ A)} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                 (δ {A} {op-time op} {τ}) idᵗ)
           (v , k))
    ≡⟨⟩
      map-carrier (opᵀ op)
        (map-carrier
          (mapˣᵗ {⟦ param op ⟧ᵍ} {[ op-time op + τ ]ᵒ A ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                idᵗ
                (   [ op-time op ]ᶠ (   map⇒ᵐ {⟦ arity op ⟧ᵍ} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ} {Tᵒ (A ×ᵗ B) τ} idᵗ (strᵀ {A} {B} {τ})
                                     ∘ᵗ curryᵗ
                                          {[ τ ]ᵒ A ×ᵗ ((⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ))} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ}
                                          ⟨    fstᵗ {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                                            ∘ᵗ fstᵗ {_} {⟦ arity op ⟧ᵍ} ,
                                            uncurryᵗ
                                              {[ τ ]ᵒ A ×ᵗ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} {⟦ arity op ⟧ᵍ} {Tᵒ B τ}
                                              (sndᵗ {[ τ ]ᵒ A}) ⟩ᵗ)
                 ∘ᵗ []-monoidal {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                 ∘ᵗ mapˣᵗ
                      {[ op-time op + τ ]ᵒ A} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                      {[ op-time op ]ᵒ ([ τ ]ᵒ A)} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                      (δ {A} {op-time op} {τ}) idᵗ))
          (w , v , k))
    ≡⟨⟩
      map-carrier (opᵀ op)
        (map-carrier
          (mapˣᵗ {⟦ param op ⟧ᵍ} {[ op-time op + τ ]ᵒ A ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                idᵗ
                (   [ op-time op ]ᶠ (   map⇒ᵐ {⟦ arity op ⟧ᵍ} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ} {Tᵒ (A ×ᵗ B) τ} idᵗ (strᵀ {A} {B} {τ})
                                     ∘ᵗ curryᵗ
                                          {[ τ ]ᵒ A ×ᵗ ((⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ))} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ}
                                          ⟨    fstᵗ {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                                            ∘ᵗ fstᵗ {_} {⟦ arity op ⟧ᵍ} ,
                                            uncurryᵗ
                                              {[ τ ]ᵒ A ×ᵗ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} {⟦ arity op ⟧ᵍ} {Tᵒ B τ}
                                              (sndᵗ {[ τ ]ᵒ A}) ⟩ᵗ)
                 ∘ᵗ []-monoidal {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                 ∘ᵗ mapˣᵗ
                      {[ op-time op + τ ]ᵒ A} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                      {[ op-time op ]ᵒ ([ τ ]ᵒ A)} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                      (δ {A} {op-time op} {τ}) idᵗ))
          (map-carrier
            (⟨    fstᵗ {⟦ param op ⟧ᵍ} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
               ∘ᵗ sndᵗ {[ op-time op + τ ]ᵒ A} ,
               ⟨ fstᵗ {[ op-time op + τ ]ᵒ A} {⟦ param op ⟧ᵍ ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} ,
                    sndᵗ {⟦ param op ⟧ᵍ} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                 ∘ᵗ sndᵗ {[ op-time op + τ ]ᵒ A} {⟦ param op ⟧ᵍ ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} ⟩ᵗ ⟩ᵗ)
            (v , w , k)))
    ≡⟨⟩
      map-carrier (opᵀ op)
        (map-carrier
          (   mapˣᵗ {⟦ param op ⟧ᵍ} {[ op-time op + τ ]ᵒ A ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                idᵗ
                (   [ op-time op ]ᶠ (   map⇒ᵐ {⟦ arity op ⟧ᵍ} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ} {Tᵒ (A ×ᵗ B) τ} idᵗ (strᵀ {A} {B} {τ})
                                     ∘ᵗ curryᵗ
                                          {[ τ ]ᵒ A ×ᵗ ((⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ))} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ}
                                          ⟨    fstᵗ {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                                            ∘ᵗ fstᵗ {_} {⟦ arity op ⟧ᵍ} ,
                                            uncurryᵗ
                                              {[ τ ]ᵒ A ×ᵗ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} {⟦ arity op ⟧ᵍ} {Tᵒ B τ}
                                              (sndᵗ {[ τ ]ᵒ A}) ⟩ᵗ)
                 ∘ᵗ []-monoidal {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                 ∘ᵗ mapˣᵗ
                      {[ op-time op + τ ]ᵒ A} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                      {[ op-time op ]ᵒ ([ τ ]ᵒ A)} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                      (δ {A} {op-time op} {τ}) idᵗ)
           ∘ᵗ ⟨    fstᵗ {⟦ param op ⟧ᵍ} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                ∘ᵗ sndᵗ {[ op-time op + τ ]ᵒ A} ,
                ⟨ fstᵗ {[ op-time op + τ ]ᵒ A} {⟦ param op ⟧ᵍ ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} ,
                     sndᵗ {⟦ param op ⟧ᵍ} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                  ∘ᵗ sndᵗ {[ op-time op + τ ]ᵒ A} {⟦ param op ⟧ᵍ ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} ⟩ᵗ ⟩ᵗ)
          (v , w , k))
    ≡⟨⟩
      map-carrier
      (   opᵀ op
       ∘ᵗ mapˣᵗ {⟦ param op ⟧ᵍ} {[ op-time op + τ ]ᵒ A ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
            idᵗ
            (   [ op-time op ]ᶠ (   map⇒ᵐ {⟦ arity op ⟧ᵍ} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ} {Tᵒ (A ×ᵗ B) τ} idᵗ (strᵀ {A} {B} {τ})
                                 ∘ᵗ curryᵗ
                                      {[ τ ]ᵒ A ×ᵗ ((⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ))} {⟦ arity op ⟧ᵍ} {[ τ ]ᵒ A ×ᵗ Tᵒ B τ}
                                      ⟨    fstᵗ {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
                                        ∘ᵗ fstᵗ {_} {⟦ arity op ⟧ᵍ} ,
                                        uncurryᵗ
                                          {[ τ ]ᵒ A ×ᵗ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} {⟦ arity op ⟧ᵍ} {Tᵒ B τ}
                                          (sndᵗ {[ τ ]ᵒ A}) ⟩ᵗ)
             ∘ᵗ []-monoidal {[ τ ]ᵒ A} {⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ}
             ∘ᵗ mapˣᵗ
                  {[ op-time op + τ ]ᵒ A} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                  {[ op-time op ]ᵒ ([ τ ]ᵒ A)} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
                  (δ {A} {op-time op} {τ}) idᵗ)
       ∘ᵗ ⟨    fstᵗ {⟦ param op ⟧ᵍ} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
            ∘ᵗ sndᵗ {[ op-time op + τ ]ᵒ A} ,
            ⟨ fstᵗ {[ op-time op + τ ]ᵒ A} {⟦ param op ⟧ᵍ ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} ,
                 sndᵗ {⟦ param op ⟧ᵍ} {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)}
              ∘ᵗ sndᵗ {[ op-time op + τ ]ᵒ A} {⟦ param op ⟧ᵍ ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ)} ⟩ᵗ ⟩ᵗ)
      (v , w , k)
    ∎ }
-}

