--------------------------------------------------------------------
-- [-]-strong free graded monad generated by algebraic operations --
--------------------------------------------------------------------

module Semantics.Model.Example.TSets.Monad.Handling.Properties.Unit where

open import Function

open import Data.Empty
open import Data.Product
open import Data.Unit hiding (_≤_)

open import Semantics.Model.Example.TSets.TSets
open import Semantics.Model.Example.TSets.Modality.Future
open import Semantics.Model.Example.TSets.Modality.Past
open import Semantics.Model.Example.TSets.Monad.Core
open import Semantics.Model.Example.TSets.Monad.Handling

open import Semantics.Model.Category.Derived TSetCat renaming (map⇒ᵐ to map⇒ᵗ)

open import Util.Equality
open import Util.Operations
open import Util.Time

-- T-alg-of-handlerᵀ's interaction with the unit of the graded monad

T-alg-of-handlerᵀ-ηᵀ : ∀ {A τ}
                     →    uncurryᵗ T-alg-of-handlerᵀ
                       ∘ᵗ mapˣᵗ idᵗ (ηᵀ {Tᵒ A τ})
                    ≡ᵗ sndᵗ

T-alg-of-handlerᵀ-ηᵀ {A} {τ} =
  eqᵗ (λ { {t} (H , c) → refl })
