---------------------------------------------------------
-- Free graded monad generated by algebraic operations --
---------------------------------------------------------

-- Note: A version of the monad that is not quotioned by
--       the delay equations (identity and composition)

open import Function

open import Data.Empty
open import Data.Product
open import Data.Unit hiding (_≤_)

open import Semantics.TSets
open import Semantics.Modality.Future
open import Semantics.Modality.Past

open import Util.HProp
open import Util.Equality
open import Util.Operations
open import Util.Time

module Semantics.Monad where

-- Interpretation of ground types
---------------------------------

⟦_⟧ᵍ : GType → TSet
⟦ Base B ⟧ᵍ   = ConstTSet (BaseSet B)
⟦ Unit ⟧ᵍ     = 𝟙ᵗ
⟦ Empty ⟧ᵍ    = 𝟘ᵗ
⟦ [ τ ]ᵍ A ⟧ᵍ = [ τ ]ᵒ ⟦ A ⟧ᵍ


-- The free graded monad generated by the operations in Op
----------------------------------------------------------

-- Object mapping and time-monotonicity

mutual

  data Tˢ (A : TSet) : (τ : Time) → (t : Time) → Set where

    leaf  : ∀ {t}
          → carrier A t
          → Tˢ A 0 t
       
    node  : ∀ {τ t}
          → (op : Op)
          → carrier ⟦ param op ⟧ᵍ t
          → (k : {t' : Time} → t + op-time op ≤ t'
                             → carrier ⟦ arity op ⟧ᵍ t'
                             → Tˢ A τ t')
          → ({t' t'' : Time} → (p : t' ≤ t'')                                       -- time-naturality of continuation
                             → (q : t + op-time op ≤ t')
                             → (y : carrier ⟦ arity op ⟧ᵍ t')
                             → k (≤-trans q p) (monotone (⟦ arity op ⟧ᵍ) p y)
                             ≡ Tˢ-≤t p (k q y))
          → Tˢ A (op-time op + τ) t
     
    delay : ∀ {τ' t}
          → (τ : Time)
          → Tˢ A τ' (t + τ)
          → Tˢ A (τ + τ') t


  Tˢ-≤t : ∀ {A τ t t'} → t ≤ t' → Tˢ A τ t → Tˢ A τ t'
  Tˢ-≤t {A} p (leaf v) =
    leaf (monotone A p v)
  Tˢ-≤t p (node op v k k-nat) =
    node op
      (monotone (⟦ param op ⟧ᵍ) p v)
      (λ q y → k (≤-trans (+-monoˡ-≤ (op-time op) p) q) y)
      (λ p q y →
        trans
          (cong (λ q → k q (monotone ⟦ arity op ⟧ᵍ p y)) (≤-irrelevant _ _))
          (k-nat _ _ y))
  Tˢ-≤t p (delay τ k) =
    delay τ (Tˢ-≤t (+-monoˡ-≤ τ p) k)


-- Reflexivity and transitivity of time-monotonicity

Tˢ-≤t-refl : ∀ {A τ t} → (c : Tˢ A τ t) → Tˢ-≤t ≤-refl c ≡ c
Tˢ-≤t-refl {A} (leaf v) =
  cong leaf (monotone-refl A v)
Tˢ-≤t-refl {A = A} {t = t} (node {τ = τ} op v k k-nat) =
  dcong₃ (node op)
    (monotone-refl ⟦ param op ⟧ᵍ v)
    (ifun-ext (fun-ext (λ p → fun-ext (λ y →
      trans
        (cong (λ (k : {t' : Time} → t + op-time op ≤ t' → carrier ⟦ arity op ⟧ᵍ t' → Tˢ A τ t') → k p y)
          {subst (λ _ → {t' : Time} → t + op-time op ≤ t' → carrier ⟦ arity op ⟧ᵍ t' → Tˢ A τ t')
              (monotone-refl ⟦ param op ⟧ᵍ v)
              (λ q → k (≤-trans (+-monoˡ-≤ (op-time op) ≤-refl) q))}
          (subst-const _ (monotone-refl ⟦ param op ⟧ᵍ v) _))
        (cong (λ p → k p y) (≤-irrelevant _ _))))))
    (ifun-ext (ifun-ext (fun-ext (λ p → fun-ext (λ q → fun-ext (λ y → uip))))))
Tˢ-≤t-refl (delay τ k) =
  cong (delay τ)
    (trans
      (cong (λ p → Tˢ-≤t p k) (≤-irrelevant _ _))
      (Tˢ-≤t-refl k))

Tˢ-≤t-trans : ∀ {A τ t t' t''}
            → (p : t ≤ t') → (q : t' ≤ t'') → (c : Tˢ A τ t)
            → Tˢ-≤t q (Tˢ-≤t p c) ≡ Tˢ-≤t (≤-trans p q) c
Tˢ-≤t-trans {A} p q (leaf v) =
  cong leaf (monotone-trans A p q v)
Tˢ-≤t-trans {A = A} {t'' = t''} p q (node {τ = τ} op v k k-nat) =
  dcong₃ (node op)
    (monotone-trans (⟦ param op ⟧ᵍ) p q v)
    (ifun-ext (fun-ext (λ r → fun-ext (λ y →
      trans
        (cong (λ (k : {t''' : Time} → t'' + op-time op ≤ t''' → carrier ⟦ arity op ⟧ᵍ t''' → Tˢ A τ t''') → k r y)
          {subst
            (λ _ → {t' = t''' : Time} → t'' + op-time op ≤ t''' → carrier ⟦ arity op ⟧ᵍ t''' → Tˢ A τ t''')
            (monotone-trans ⟦ param op ⟧ᵍ p q v)
            (λ r → k (≤-trans (+-monoˡ-≤ (op-time op) p) (≤-trans (+-monoˡ-≤ (op-time op) q) r)))}
          (subst-const _ (monotone-trans ⟦ param op ⟧ᵍ p q v) _))
        (cong (λ p → k p y) (≤-irrelevant _ _))))))
    (ifun-ext (ifun-ext (fun-ext (λ p → fun-ext (λ q → fun-ext (λ y → uip))))))
Tˢ-≤t-trans p q (delay τ k) =
  cong (delay τ)
    (trans
      (Tˢ-≤t-trans (+-monoˡ-≤ τ p) (+-monoˡ-≤ τ q) k)
      (cong (λ p → Tˢ-≤t p k) (≤-irrelevant _ _)))


-- "subst" for time-gradings

τ-subst : ∀ {A τ τ' t}
        → τ ≡ τ'
        → Tˢ A τ t
        → Tˢ A τ' t
τ-subst refl c = c

τ-subst-≤t : ∀ {A τ τ' t t'}
           → (p : τ ≡ τ')
           → (q : t ≤ t')
           → (c : Tˢ A τ t)
           → Tˢ-≤t q (τ-subst p c) ≡ τ-subst p (Tˢ-≤t q c)
τ-subst-≤t refl q c = refl


-- Functorial action (TODO: prove identity and composition laws)

mutual

  -- TODO: investigate how to convince Agda's termination checker;
  --       the "suspicious" recursive occurrences of `Tˢᶠ` are in 
  --       types (but still applied to the continuation `k`);
  --       so maybe it is enough to index the trees by their height
  --
  --       same also applies for definitions below

  {-# TERMINATING #-}

  Tˢᶠ : ∀ {A B τ} → A →ᵗ B → {t : Time} → Tˢ A τ t → Tˢ B τ t
  Tˢᶠ f (leaf v) =
    leaf (map-carrier f v)
  Tˢᶠ f (node op v k k-nat) =
    node op v
      (λ p y → Tˢᶠ f (k p y))
      (λ p q y →
        trans
          (cong (Tˢᶠ f) (k-nat p q y))
          (Tˢᶠ-≤t-nat f p (k q y)))    
  Tˢᶠ f (delay τ k) =
    delay τ (Tˢᶠ f k)

  Tˢᶠ-≤t-nat : ∀ {A B τ} → (f : A →ᵗ B) → {t t' : ℕ}
             → (p : t ≤ t') → (c : Tˢ A τ t)
             → Tˢᶠ f (Tˢ-≤t p c) ≡ Tˢ-≤t p (Tˢᶠ f c)
  Tˢᶠ-≤t-nat f p (leaf v) =
    cong leaf (map-nat f p v)
  Tˢᶠ-≤t-nat f p (node op v k k-nat) =
    dcong₃ (node op)
      refl
      refl
      (ifun-ext (ifun-ext (fun-ext (λ p → fun-ext (λ q → fun-ext (λ y → uip))))))
  Tˢᶠ-≤t-nat f p (delay τ k) =
    cong (delay τ) (Tˢᶠ-≤t-nat f (+-monoˡ-≤ τ p) k)


-- Packaging it all up into a functor on TSet

abstract 
  Tᵒ : TSet → Time → TSet
  Tᵒ A τ = tset (Tˢ A τ) Tˢ-≤t Tˢ-≤t-refl Tˢ-≤t-trans

  Tᶠ : ∀ {A B τ} → A →ᵗ B → Tᵒ A τ →ᵗ Tᵒ B τ
  Tᶠ f = tset-map (Tˢᶠ f) (Tˢᶠ-≤t-nat f)


-- Unit (TODO: prove naturality and laws)

abstract
  ηᵀ : ∀ {A} → A →ᵗ Tᵒ A 0
  ηᵀ =
    tset-map
      (λ v → leaf v)
      (λ p v → refl)


-- Multiplication (TODO: prove naturality and laws)

mutual abstract

  {-# TERMINATING #-}

  μˢ : ∀ {A τ τ'} → {t : Time}
     → Tˢ (Tᵒ A τ') τ t → Tˢ A (τ + τ') t
  μˢ (leaf c) =
    c
  μˢ (node op v k k-nat) =
    τ-subst
      (sym (+-assoc (op-time op) _ _))
      (node op v
        (λ p y → μˢ (k p y))
        (λ p q y →
          trans
            (cong μˢ (k-nat p q y))
            (μˢ-≤t-nat p (k q y))))
  μˢ (delay τ k) =
    τ-subst (sym (+-assoc τ _ _)) (delay τ (μˢ k))

  μˢ-≤t-nat : ∀ {A τ τ'} → {t t' : ℕ}
          → (p : t ≤ t')
          → (c : Tˢ (Tᵒ A τ') τ t)
          → μˢ (Tˢ-≤t p c) ≡ Tˢ-≤t p (μˢ c)
  μˢ-≤t-nat p (leaf v) =
    refl
  μˢ-≤t-nat p (node op v k k-nat) =
    trans
      (cong (τ-subst (sym (+-assoc (op-time op) _ _)))
        (dcong₂ (node op (monotone ⟦ param op ⟧ᵍ p v))
          refl
          (ifun-ext (ifun-ext (fun-ext (λ q → fun-ext (λ r → fun-ext (λ y → uip))))))))
      (sym (τ-subst-≤t (sym (+-assoc (op-time op) _ _)) p _))
  μˢ-≤t-nat p (delay τ k) =
    trans
      (cong
        (τ-subst (sym (+-assoc τ _ _)))
        (cong (delay τ) (μˢ-≤t-nat (+-monoˡ-≤ τ p) k)))
      (sym (τ-subst-≤t (sym (+-assoc τ _ _)) p (delay τ (μˢ k))))

abstract
  μᵀ : ∀ {A τ τ'}
     → Tᵒ (Tᵒ A τ') τ →ᵗ Tᵒ A (τ + τ')
  μᵀ = tset-map μˢ μˢ-≤t-nat


-- Strength (TODO: prove naturality and laws)

mutual

  {-# TERMINATING #-}

  strˢ : ∀ {A B τ τ' t}
       → carrier ([ τ ]ᵒ (⟨ τ' ⟩ᵒ A)) t
       → Tˢ B τ t
       → Tˢ (⟨ τ' ⟩ᵒ A ×ᵗ B) τ t
  strˢ {A} {B} {τ' = τ'} {t} v (leaf w) =
    leaf
      (pack-×ᵗ
        ((≤-trans (proj₁ v) (≤-reflexive (+-identityʳ _)) ,
           monotone A
             (≤-reflexive (cong (_∸ τ') (+-identityʳ _)))
             (proj₂ v)) ,
         w))
  strˢ {A} {B} {_} {τ'} {t} v (node op w k k-nat) =
    node op w
      (λ p y →
        strˢ {A} {B}
          ((monotone (⟨ τ' ⟩ᵒ A)
             (≤-trans
               (≤-reflexive (sym (+-assoc t _ _)))
               (+-monoˡ-≤ _ p))
             v))
          (k p y))
      (λ p q y →
        trans
          (cong₂ strˢ
            (cong₂ _,_
              (≤-irrelevant _ _)
              (trans
                (cong (λ p → monotone A p (proj₂ v))
                  (≤-irrelevant _ _))
                (sym
                  (monotone-trans A _
                    (∸-monoˡ-≤ τ' (+-monoˡ-≤ _ p))
                    (proj₂ v)))))
            (k-nat p q y))
          (strˢ-≤t-nat p _ (k q y)))
  strˢ {A} {B} {_} {τ'} {t} v (delay τ k) =
    delay τ
      (strˢ {A} {B}
        (monotone (⟨ τ' ⟩ᵒ A) (≤-reflexive (sym (+-assoc t _ _))) v)
        k)
     
  strˢ-≤t-nat : ∀ {A B τ τ'} → {t t' : ℕ} → (p : t ≤ t')
              → (v : carrier ([ τ ]ᵒ (⟨ τ' ⟩ᵒ A)) t)
              → (c : Tˢ B τ t)
              → strˢ {A = A} {B = B}
                  (monotone ([ τ ]ᵒ (⟨ τ' ⟩ᵒ A)) p v)
                  (Tˢ-≤t p c)
              ≡ Tˢ-≤t p (strˢ {A = A} {B = B} v c)
  strˢ-≤t-nat {A} {B} p v (leaf w) =
    cong leaf
      (trans
        (cong pack-×ᵗ
          (cong (_, monotone B p w)
            (cong₂ _,_
              (≤-irrelevant _ _)
              (trans
                (trans
                  (monotone-trans A _ _ (proj₂ v))
                  (cong (λ p → monotone A p (proj₂ v)) (≤-irrelevant _ _)))
                (sym (monotone-trans A _ _ (proj₂ v)))))))
        (sym (pack-×ᵗ-monotone p _)))
  strˢ-≤t-nat {A} {B} p v (node op w k k-nat) =
    dcong₂ (node op (monotone ⟦ param op ⟧ᵍ p w))
      (ifun-ext (fun-ext (λ q → fun-ext (λ y →
        cong (λ v → strˢ {A} {B} v (k (≤-trans (+-monoˡ-≤ (op-time op) p) q) y))
          (cong₂ _,_
            (≤-irrelevant _ _)
            (trans
              (monotone-trans A _ _ (proj₂ v))
              (cong (λ p → monotone A p (proj₂ v)) (≤-irrelevant _ _))))))))
      (ifun-ext (ifun-ext (fun-ext (λ q → fun-ext (λ r → fun-ext (λ y → uip))))))
  strˢ-≤t-nat {A} {B} {_} {τ'} {t} {t'} p v (delay τ k) =
    cong (delay τ)
      (trans
        (cong (λ v → strˢ {A} {B} v (Tˢ-≤t (+-monoˡ-≤ _ p) k))
          (cong₂ _,_
            (≤-irrelevant _ _)
            (trans
              (monotone-trans A _ _ (proj₂ v))
              (trans
                (cong (λ p → monotone A p (proj₂ v)) (≤-irrelevant _ _))
                (sym (monotone-trans A _ _ (proj₂ v)))))))
        (strˢ-≤t-nat
          (+-monoˡ-≤ τ p)
          (monotone (⟨ τ' ⟩ᵒ A) (≤-reflexive (sym (+-assoc t _ _))) v)
          k))

abstract
  strᵀ : ∀ {A B τ τ'}
       → [ τ ]ᵒ (⟨ τ' ⟩ᵒ A) ×ᵗ Tᵒ B τ →ᵗ Tᵒ (⟨ τ' ⟩ᵒ A ×ᵗ B) τ
  strᵀ {A} {B} {τ} {τ'} =
    tset-map
      (λ vc → strˢ {A} {B} (proj₁ (unpack-×ᵗ vc)) (proj₂ (unpack-×ᵗ vc)))
      (λ p vc → trans
        (cong₂ strˢ
          (sym (cong proj₁ (unpack-×ᵗ-monotone {[ τ ]ᵒ (⟨ τ' ⟩ᵒ A)} {Tᵒ B τ} p vc)))
          (sym (cong proj₂ (unpack-×ᵗ-monotone {[ τ ]ᵒ (⟨ τ' ⟩ᵒ A)} {Tᵒ B τ} p vc))))
        (strˢ-≤t-nat p _ _))


-- Delay operation (T is a kind of a [_]-module)

abstract
  delayᵀ : ∀ {A} (τ : Time) {τ'} → [ τ ]ᵒ (Tᵒ A τ') →ᵗ Tᵒ A (τ + τ')
  delayᵀ τ =
    tset-map
      (delay τ)
      (λ p c → refl)


-- Algebraic operations

abstract
  opᵀ : ∀ {A τ} → (op : Op)
      → ⟦ param op ⟧ᵍ ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ A τ) →ᵗ Tᵒ A (op-time op + τ)
  opᵀ {A} {τ} op =
    tset-map
      (λ {t} vk →
        node op
          (proj₁ (unpack-×ᵗ vk))
          (λ p y →
            map-carrier
              (unpack-⇒ᵗ (proj₂ (unpack-×ᵗ vk)))
              (pack-×ᵗ (pack-homᵒ (t + op-time op) p , y)))
          (λ p q y →
            trans
              (cong (map-carrier (unpack-⇒ᵗ (proj₂ (unpack-×ᵗ vk))))
                (trans
                  (cong pack-×ᵗ
                    (cong (_, monotone ⟦ arity op ⟧ᵍ p y)
                      (sym (pack-homᵒ-monotone _ _))))
                  (sym (pack-×ᵗ-monotone _ _))))
              (map-nat (unpack-⇒ᵗ (proj₂ (unpack-×ᵗ vk))) _ _)))
      (λ {t} {t'} p k →
        dcong₃ (node op)
          (sym (cong proj₁ (unpack-×ᵗ-monotone _ k)))
          (ifun-ext (fun-ext (λ q → fun-ext (λ y →
            trans
              (cong (λ (k : {t' : Time} → _ + op-time op ≤ t' → carrier ⟦ arity op ⟧ᵍ t' → Tˢ A _ t') → k q y)
                (subst-const _ (sym (cong proj₁ (unpack-×ᵗ-monotone p k))) _))
              {!!}))))
          (ifun-ext (ifun-ext (fun-ext (λ q → fun-ext (λ r → fun-ext (λ y → uip)))))))


-- {(λ p₁ y₁ → map-carrier (unpack-⇒ᵗ (proj₂ (unpack-×ᵗ (monotone (⟦ param op ⟧ᵍ ×ᵗ [ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ A _)) p k)))) (pack-×ᵗ (pack-homᵒ (_ + op-time op) p₁ , y₁)))}


-- Effect handling / free algebras

mutual abstract

  {-# TERMINATING #-}

  handleˢ : ∀ {A B τ τ' t}
          → ((op : Op) → (τ'' : Time) →
               ⟦ param op ⟧ᵍ ×ᵗ ([ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ'')) →ᵗ Tᵒ B (op-time op + τ''))
          → A →ᵗ Tᵒ B τ'
          → Tˢ A τ t
          → Tˢ B (τ + τ') t
  handleˢ h f (leaf v) =
    map-carrier f v
  handleˢ {A} {B} {t = t} h f (node op v k k-nat) =
    τ-subst
      (sym (+-assoc (op-time op) _ _))
      (map-carrier (h op _)
        (pack-×ᵗ (v ,
          pack-⇒ᵗ
            (tset-map
              (λ py →
                handleˢ h f
                  (k (unpack-homᵒ (t + op-time op) (proj₁ (unpack-×ᵗ py)))
                     (proj₂ (unpack-×ᵗ py))))
              (λ p qy → trans
                (cong
                  (handleˢ {A} {B} h f)
                  {k (unpack-homᵒ (t + op-time op)
                       (proj₁ (unpack-×ᵗ (monotone (homᵒ (t + op-time op) ×ᵗ ⟦ arity op ⟧ᵍ) p qy))))
                     (proj₂ (unpack-×ᵗ (monotone (homᵒ (t + op-time op) ×ᵗ ⟦ arity op ⟧ᵍ) p qy)))}
                  {Tˢ-≤t p (k (unpack-homᵒ (t + op-time op) (proj₁ (unpack-×ᵗ qy))) (proj₂ (unpack-×ᵗ qy)))}
                  (trans
                    (cong₂ k
                      (≤-irrelevant _ _)
                      (sym (cong proj₂ (unpack-×ᵗ-monotone {homᵒ (t + op-time op)} {⟦ arity op ⟧ᵍ} p qy))))
                    (k-nat p (unpack-homᵒ (t + op-time op) (proj₁ (unpack-×ᵗ qy))) (proj₂ (unpack-×ᵗ qy)))))
                (handleˢ-≤t-nat p h f (k (unpack-homᵒ (t + op-time op) (proj₁ (unpack-×ᵗ qy))) (proj₂ (unpack-×ᵗ qy)))))))))
  handleˢ h f (delay τ k) =
    τ-subst
      (sym (+-assoc τ _ _))
      (delay τ (handleˢ h f k))

  handleˢ-≤t-nat : ∀ {A B τ τ'} → {t t' : ℕ} → (p : t ≤ t')
                 → (h : (op : Op) → (τ'' : Time) →
                          ⟦ param op ⟧ᵍ ×ᵗ ([ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ'')) →ᵗ Tᵒ B (op-time op + τ''))
                 → (f : A →ᵗ Tᵒ B τ')
                 → (c : Tˢ A τ t)
                 → handleˢ h f (Tˢ-≤t p c)
                 ≡ Tˢ-≤t p (handleˢ h f c)
  handleˢ-≤t-nat p h f (leaf v) =
    map-nat f p v
  handleˢ-≤t-nat {A} {B} {τ' = τ'} p h f (node {τ = τ} op v k k-nat) =
    trans
      (cong (τ-subst (sym (+-assoc (op-time op) τ τ')))
        (trans
          (cong (map-carrier (h op (τ + τ')))
            (trans
              (cong pack-×ᵗ
                (cong (monotone ⟦ param op ⟧ᵍ p v ,_)
                  (trans
                    (cong pack-⇒ᵗ
                      (dcong₂ tset-map
                        (ifun-ext (fun-ext (λ qy →
                          cong₂ (λ q y → handleˢ h f (k q y))
                            (≤-irrelevant _ _)
                            (sym (cong proj₂ (pack-unpack-×ᵗ _))))))
                        (ifun-ext (ifun-ext (fun-ext (λ q → fun-ext (λ ry → uip)))))))
                    (sym (pack-⇒ᵗ-monotone _ _)))))
              (sym
                (pack-×ᵗ-monotone
                  {⟦ param op ⟧ᵍ}
                  {[ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B (τ + τ'))}
                  p _))))
          (map-nat (h op (τ + τ')) p _)))
      (sym (τ-subst-≤t (sym (+-assoc (op-time op) τ τ')) p _))
  handleˢ-≤t-nat p h f (delay τ k) =
    trans
      (cong (τ-subst (sym (+-assoc τ _ _)))
        (cong (delay τ)
          (handleˢ-≤t-nat (+-monoˡ-≤ τ p) h f k)))
      (sym (τ-subst-≤t (sym (+-assoc τ _ _)) p
             (delay τ (handleˢ h f k))))

abstract
  handleᵀ : ∀ {A B τ τ'}
          → ((op : Op) → (τ'' : Time) →
               ⟦ param op ⟧ᵍ ×ᵗ ([ op-time op ]ᵒ (⟦ arity op ⟧ᵍ ⇒ᵗ Tᵒ B τ'')) →ᵗ Tᵒ B (op-time op + τ''))
          → A →ᵗ Tᵒ B τ'
          → Tᵒ A τ →ᵗ Tᵒ B (τ + τ')
  handleᵀ h f =
    tset-map (handleˢ h f) (λ p → handleˢ-≤t-nat p h f)































---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------


{-


-- Candidate for object-mapping of the underlying functor to support quotienting by delay equations
-- NOTE: quick sketch, does not include naturality condition for operation nodes


mutual
  
  data Tˢ (A : TSet) : (τ : Time) → (t : Time) → Set where  -- 1st time index (τ) is the duration of the computation (its time-grading)
                                                            -- 2nd time index (t) is the corresponding TSets' time-index (presheaf index)
    delay : ∀ {τ' t}
          → (τ : Time)
          → 0 < τ
          → Tᶜˢ A τ' (t + τ)
          → Tˢ A (τ + τ') t
    comp  : ∀ {τ t}
          → Tᶜˢ A τ t
          → Tˢ A τ t
  data Tᶜˢ (A : TSet) : (τ : Time) → (t : Time) → Set where  -- 1st time index (τ) is the duration of the computation (its time-grading)
                                                             -- 2nd time index (t) is the corresponding TSets' time-index (presheaf index)
    leaf  : ∀ {t}
          → carrier A t
          → Tᶜˢ A 0 t
     
    node  : ∀ {τ t}
          → (op : Op)
          → carrier ⟦ param op ⟧ᵍ t
          → ({t' : Time} → t + op-time op ≤ t'
                         → carrier ⟦ arity op ⟧ᵍ t'
                         → Tˢ A τ t')
          → Tᶜˢ A (op-time op + τ) t

-}
